version: "3.7"

services:
  pghost:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: pguser
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes: 
      - pgericadata:/var/lib/postgresql/data

volumes:
  pgericadata:
    external: true
# para criar este volume:
# docker volume create grafanadata